# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to='file'),
        ),
    ]
